namespace Core.Entities
{
    public class CustomerBasket
    {
        //the redis first have to create a basket and then attach the id
        public CustomerBasket()
        {
        }

        //just id as the basket is empty right after the creation
        public CustomerBasket(string id)
        {
            Id = id;
        }

        //generated by the client
        //redis consumes the data as key value string
        //key: basket.Id, value: basket
        //this is why its more convenient to use string instead of int
        public string Id { get; set; }
        public List<BasketItem> Items { get; set; } = new();
    }
}